;;; ob-sql-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from ob-sql-mode.el

(register-definition-prefixes "ob-sql-mode" '("org-babel-"))

;;; End of scraped data

(provide 'ob-sql-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ob-sql-mode-autoloads.el ends here
