;;; babel-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from babel.el

(autoload 'babel "babel" "\
Use a web translation service to translate the message MSG.
Display the result in a buffer *babel* unless the optional argument
NO-DISPLAY is nil.

If the output is short enough to display in the echo area (which is
determined by the variables `resize-mini-windows' and
`max-mini-window-height'), it is shown there, but it is nonetheless
available in buffer `*babel*' even though that buffer is not
automatically displayed.

(fn MSG &optional NO-DISPLAY ACCEPT-DEFAULT-SETUP)" t)
(autoload 'babel-region "babel" "\
Use a web translation service to translate the current region.
With prefix argument, yank the translation to the kill-ring.

(fn START END &optional ARG)" t)
(autoload 'babel-as-string "babel" "\
Use a web translation service to translate MSG, returning a string.

(fn MSG)" t)
(autoload 'babel-buffer "babel" "\
Use a web translation service to translate the current buffer.
Default is to present the translated text in a *babel* buffer.
With a prefix argument, replace the current buffer contents by the
translated text." t)
(autoload 'babel-version "babel" "\
Show the version number of babel in the minibuffer.
If optional argument HERE is non-nil, insert version number at point.

(fn &optional HERE)" t)
(register-definition-prefixes "babel" '("babel-" "json-get" "mm-encode-coding-string"))

;;; End of scraped data

(provide 'babel-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; babel-autoloads.el ends here
