;;; ob-rust-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from ob-rust.el

(register-definition-prefixes "ob-rust" '("org-babel-"))


;;; Generated autoloads from test-ob-rust.el

(register-definition-prefixes "test-ob-rust" '("ob-rust-test-" "org-"))

;;; End of scraped data

(provide 'ob-rust-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ob-rust-autoloads.el ends here
