;;; ffmpeg-utils-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from ffmpeg-utils.el

(register-definition-prefixes "ffmpeg-utils" '("ffmpeg-utils-"))

;;; End of scraped data

(provide 'ffmpeg-utils-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ffmpeg-utils-autoloads.el ends here
