;;; dired-launch-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from dired-launch.el

(autoload 'dired-launch-command "dired-launch" "\
Attempt to launch appropriate executables on marked files in the
current dired buffer." t)
(autoload 'dired-launch-with-prompt-command "dired-launch" "\
For each marked file in the current dired buffer, prompt user to
specify an executable and then call the specified executable using
that file." t)
(autoload 'dired-launch-mode "dired-launch" "\
Add commands to launch executables.

This is a minor mode.  If called interactively, toggle the `Dired-Launch
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `dired-launch-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'dired-launch-enable "dired-launch" "\
Ensure that `dired-launch-mode' will be enabled in `dired-mode'." t)
(register-definition-prefixes "dired-launch" '("dired-launch-"))


;;; Generated autoloads from dired-launch-x-on-dir.el

(register-definition-prefixes "dired-launch-x-on-dir" '("dat-launch-x--windows" "dired-launch-"))

;;; End of scraped data

(provide 'dired-launch-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dired-launch-autoloads.el ends here
