;;; ob-php-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from ob-php.el

(autoload 'org-babel-execute:php "ob-php" "\
Orgmode Babel PHP evaluate function for `BODY' with `PARAMS'.

(fn BODY PARAMS)")
(eval-after-load 'org '(add-to-list 'org-src-lang-modes '("php" . php)))
(register-definition-prefixes "ob-php" '("ob-php:inf-php-buffer" "org-babel-"))

;;; End of scraped data

(provide 'ob-php-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ob-php-autoloads.el ends here
