fx_bubble="🫧🫧 🫧 🫧 🫧 🫧🫧 🫧🫧 🫧 🫧🫧"
fx_ocean="🌊🪸🪼 💦🌊🌊🐬🫧🌊🫧⛵ 🫧 🌊🫧"
fx_magic="✨🪄 ✨🌟✨✨ 💫 ✨🧙🏿✨ 🔥✨"
fx_fire="🔥 🔥🔥 🔥 🔥🔥⽕🔥 🔥🔥 🔥 🔥🔥"
fx_ice="❄️❄️❄️ ❄️ ❄️☃️ ❄️❄️ ❄️ ❄️❄️ ❄️❄️"
fx_zap="⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡"
fx_lines="---=====----=====----=====-----"
fx_space="👽🪐👾🌌🚀🛸🛰️"
fx_fairytale="🧚🏾🦋✨🍄🐛📔🍎"
fx_squares="#⏹️🟦◻"
fx_trains="🚂🚄🚃🛤️"
fx_musical="🎼 🎵🎶🎵 🎹 🎷 🎵 🎸 🎶"
fx_grass=""
fx_mumble=""
fx_fizzle=""
fx_sunlight=""

